import mongoose from "mongoose";

const UserSchema = new mongoose.Schema({
    username:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    refreshToken:String,
    joindate:{
        type:String
    },
    tests:{
        tchallenges:{
            type:Number,
            default:0
        },
        tpractices:{
            type:Number,    
            default:0
        },
        ttime:{
            type:Number,
            default:0
        },
    },
    records:{
        modeTime:{
            fifteen:{
                wpm:{
                    type:Number,
                    default:0
                },
                accuracy:{
                    type:Number,
                    default:0
                }
            },
            thirty:{
                wpm:{
                    type:Number,
                    default:0
                },
                accuracy:{
                    type:Number,
                    default:0
                }
            },
            sixty:{
                wpm:{
                    type:Number,
                    default:0
                },
                accuracy:{
                    type:Number,
                    default:0
                }
            },
            onetwenty:{
                wpm:{
                    type:Number,
                    default:0
                },
                accuracy:{
                    type:Number,
                    default:0
                }
            }
        },
        modeWords:{
            twenty:{
                wpm:{
                    type:Number,
                    default:0
                },
                accuracy:{
                    type:Number,
                    default:0
                }
            },
            fifty:{
                wpm:{
                    type:Number,
                    default:0
                },
                accuracy:{
                    type:Number,
                    default:0
                }
            },
            seventy:{
                wpm:{
                    type:Number,
                    default:0
                },
                accuracy:{
                    type:Number,
                    default:0
                }
            },
            hundred:{
                wpm:{
                    type:Number,
                    default:0
                },
                accuracy:{
                    type:Number,
                    default:0
                }
            }

        }
    }

})

export default mongoose.model('User',UserSchema);